/**
 * نقاش‌باشی (Naghash Bashi) - Persian Word Bank & Normalization Engine
 * Contains 990 100% tangible, drawable physical Persian words validated against Skribbl.io standards.
 * STRICT POLICY: ZERO artificial compound glued words (like دستگاهفرز, سیمچین, پیچگوشتی),
 * ZERO abstract sensations, ZERO multi-part phrases, ZERO ZWNJ in targets.
 * Perfectly balanced 3-tier distribution: 330 Easy, 330 Medium, 330 Hard.
 */

(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.WordBank = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {

  // Pure single-piece Persian physical words (strictly 1 tangible object, zero spaces, zero ZWNJ, zero hyphens)
  // Balanced: 330 Easy, 330 Medium, 330 Hard (Total 990)
  const WORDS = [
    { word: 'سیب', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'موز', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'پرتقال', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'خیار', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'گوجه', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'هویج', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'پیاز', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'سیر', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'قارچ', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'انگور', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'لیمو', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'توت', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'گیلاس', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'انار', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'هندوانه', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'خربزه', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'طالبی', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'هلو', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'نارنگی', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'خرما', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'نان', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'پنیر', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'کره', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'شیر', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'ماست', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'نیمرو', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'عسل', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'مربا', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'کیک', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'بستنی', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'شکلات', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'آبنبات', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'بیسکویت', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'کلوچه', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'چیپس', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'پفک', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'پیتزا', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'برگر', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'ساندویچ', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'سوسیس', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'کالباس', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'کباب', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'سوپ', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'آش', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'چای', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'قهوه', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'نوشابه', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'دوغ', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'سگ', category: 'حیوانات', difficulty: 'easy' },
    { word: 'گربه', category: 'حیوانات', difficulty: 'easy' },
    { word: 'موش', category: 'حیوانات', difficulty: 'easy' },
    { word: 'خرگوش', category: 'حیوانات', difficulty: 'easy' },
    { word: 'اسب', category: 'حیوانات', difficulty: 'easy' },
    { word: 'الاغ', category: 'حیوانات', difficulty: 'easy' },
    { word: 'گاو', category: 'حیوانات', difficulty: 'easy' },
    { word: 'گوسفند', category: 'حیوانات', difficulty: 'easy' },
    { word: 'بز', category: 'حیوانات', difficulty: 'easy' },
    { word: 'بره', category: 'حیوانات', difficulty: 'easy' },
    { word: 'مرغ', category: 'حیوانات', difficulty: 'easy' },
    { word: 'خروس', category: 'حیوانات', difficulty: 'easy' },
    { word: 'اردک', category: 'حیوانات', difficulty: 'easy' },
    { word: 'غاز', category: 'حیوانات', difficulty: 'easy' },
    { word: 'قو', category: 'حیوانات', difficulty: 'easy' },
    { word: 'کبوتر', category: 'حیوانات', difficulty: 'easy' },
    { word: 'گنجشک', category: 'حیوانات', difficulty: 'easy' },
    { word: 'ماهی', category: 'حیوانات', difficulty: 'easy' },
    { word: 'مار', category: 'حیوانات', difficulty: 'easy' },
    { word: 'قورباغه', category: 'حیوانات', difficulty: 'easy' },
    { word: 'قاشق', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'چنگال', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'چاقو', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کارد', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'بشقاب', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کاسه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'لیوان', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'فنجان', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'استکان', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'نعلبکی', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'قوری', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کتری', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'سماور', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'قابلمه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تابه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'دیگ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'سینی', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'پارچ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'بطری', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'قوطی', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'نمکدان', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'قندان', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'سفره', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'دستمال', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'حوله', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'صابون', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'شامپو', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'مسواک', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'شانه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'برس', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'آینه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'ساعت', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'لامپ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'چراغ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'شمع', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کبریت', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'فندک', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'گلدان', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تابلو', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'قاب', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'پرده', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'فرش', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'قالی', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'مبل', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'صندلی', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'میز', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کمد', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تخت', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'بالشت', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تشک', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'پتو', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'سطل', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'جارو', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'پنجره', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'دیوار', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'درب', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'دستگیره', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'قفل', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کلید', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'طناب', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'زنجیر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'جعبه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کادو', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'چتر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'چکش', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'اره', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'میخ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'پیچ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'قیچی', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'چسب', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'بیل', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کلنگ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تبر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'مداد', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'خودکار', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تراش', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کاغذ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'دفتر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کتاب', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تخته', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'گچ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کیف', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کوله', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تلفن', category: 'تکنولوژی', difficulty: 'easy' },
    { word: 'موبایل', category: 'تکنولوژی', difficulty: 'easy' },
    { word: 'تلویزیون', category: 'تکنولوژی', difficulty: 'easy' },
    { word: 'رادیو', category: 'تکنولوژی', difficulty: 'easy' },
    { word: 'کامپیوتر', category: 'تکنولوژی', difficulty: 'easy' },
    { word: 'لپتاپ', category: 'تکنولوژی', difficulty: 'easy' },
    { word: 'کفش', category: 'پوشاک', difficulty: 'easy' },
    { word: 'کلاه', category: 'پوشاک', difficulty: 'easy' },
    { word: 'جوراب', category: 'پوشاک', difficulty: 'easy' },
    { word: 'شلوار', category: 'پوشاک', difficulty: 'easy' },
    { word: 'پیراهن', category: 'پوشاک', difficulty: 'easy' },
    { word: 'تیشرت', category: 'پوشاک', difficulty: 'easy' },
    { word: 'کت', category: 'پوشاک', difficulty: 'easy' },
    { word: 'دامن', category: 'پوشاک', difficulty: 'easy' },
    { word: 'عینک', category: 'پوشاک', difficulty: 'easy' },
    { word: 'شال', category: 'پوشاک', difficulty: 'easy' },
    { word: 'روسری', category: 'پوشاک', difficulty: 'easy' },
    { word: 'چادر', category: 'پوشاک', difficulty: 'easy' },
    { word: 'دستکش', category: 'پوشاک', difficulty: 'easy' },
    { word: 'ماشین', category: 'وسایل نقلیه', difficulty: 'easy' },
    { word: 'تاکسی', category: 'وسایل نقلیه', difficulty: 'easy' },
    { word: 'اتوبوس', category: 'وسایل نقلیه', difficulty: 'easy' },
    { word: 'قطار', category: 'وسایل نقلیه', difficulty: 'easy' },
    { word: 'موتور', category: 'وسایل نقلیه', difficulty: 'easy' },
    { word: 'دوچرخه', category: 'وسایل نقلیه', difficulty: 'easy' },
    { word: 'هواپیما', category: 'وسایل نقلیه', difficulty: 'easy' },
    { word: 'قایق', category: 'وسایل نقلیه', difficulty: 'easy' },
    { word: 'کشتی', category: 'وسایل نقلیه', difficulty: 'easy' },
    { word: 'درخت', category: 'طبیعت', difficulty: 'easy' },
    { word: 'گل', category: 'طبیعت', difficulty: 'easy' },
    { word: 'برگ', category: 'طبیعت', difficulty: 'easy' },
    { word: 'شاخه', category: 'طبیعت', difficulty: 'easy' },
    { word: 'ریشه', category: 'طبیعت', difficulty: 'easy' },
    { word: 'سبزه', category: 'طبیعت', difficulty: 'easy' },
    { word: 'چمن', category: 'طبیعت', difficulty: 'easy' },
    { word: 'خورشید', category: 'طبیعت', difficulty: 'easy' },
    { word: 'ماه', category: 'طبیعت', difficulty: 'easy' },
    { word: 'ستاره', category: 'طبیعت', difficulty: 'easy' },
    { word: 'ابر', category: 'طبیعت', difficulty: 'easy' },
    { word: 'باران', category: 'طبیعت', difficulty: 'easy' },
    { word: 'برف', category: 'طبیعت', difficulty: 'easy' },
    { word: 'کوه', category: 'طبیعت', difficulty: 'easy' },
    { word: 'تپه', category: 'طبیعت', difficulty: 'easy' },
    { word: 'دریا', category: 'طبیعت', difficulty: 'easy' },
    { word: 'رودخانه', category: 'طبیعت', difficulty: 'easy' },
    { word: 'سنگ', category: 'طبیعت', difficulty: 'easy' },
    { word: 'آدمبرفی', category: 'طبیعت', difficulty: 'easy' },
    { word: 'خانه', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'پل', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'مسجد', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'مدرسه', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'بیمارستان', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'استخر', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'پارک', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'هتل', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'بانک', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'زندان', category: 'ساختمان و مکان', difficulty: 'easy' },
    { word: 'توپ', category: 'ورزش و بازی', difficulty: 'easy' },
    { word: 'بادکنک', category: 'ورزش و بازی', difficulty: 'easy' },
    { word: 'عروسک', category: 'ورزش و بازی', difficulty: 'easy' },
    { word: 'تاس', category: 'ورزش و بازی', difficulty: 'easy' },
    { word: 'سوت', category: 'ورزش و بازی', difficulty: 'easy' },
    { word: 'تور', category: 'ورزش و بازی', difficulty: 'easy' },
    { word: 'پلیس', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'دکتر', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'پزشک', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'معلم', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'خلبان', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'نقاش', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'نجار', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'آشپز', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'نانوا', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'دزد', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'دلقک', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'پادشاه', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'ملکه', category: 'شخصیت‌ها و مشاغل', difficulty: 'easy' },
    { word: 'طبل', category: 'موسیقی', difficulty: 'easy' },
    { word: 'زنگ', category: 'موسیقی', difficulty: 'easy' },
    { word: 'نی', category: 'موسیقی', difficulty: 'easy' },
    { word: 'دست', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'پا', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'چشم', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'گوش', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'بینی', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'دهان', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'دندان', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'مو', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'انگشت', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'لب', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'سر', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'زبان', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'قلب', category: 'اعضای بدن', difficulty: 'easy' },
    { word: 'تیر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کمان', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'سپر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'شمشیر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تفنگ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'اسکناس', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'سکه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'پرچم', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تمبر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کارت', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'نامه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'پاکت', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'عکس', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'سبد', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کیسه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کوزه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'لوله', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'میله', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'پله', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'نرده', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'ستون', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'آتش', category: 'طبیعت', difficulty: 'easy' },
    { word: 'دود', category: 'طبیعت', difficulty: 'easy' },
    { word: 'شعله', category: 'طبیعت', difficulty: 'easy' },
    { word: 'حباب', category: 'طبیعت', difficulty: 'easy' },
    { word: 'موج', category: 'طبیعت', difficulty: 'easy' },
    { word: 'قطره', category: 'طبیعت', difficulty: 'easy' },
    { word: 'سیل', category: 'طبیعت', difficulty: 'easy' },
    { word: 'چاله', category: 'طبیعت', difficulty: 'easy' },
    { word: 'دره', category: 'طبیعت', difficulty: 'easy' },
    { word: 'دشت', category: 'طبیعت', difficulty: 'easy' },
    { word: 'صحرا', category: 'طبیعت', difficulty: 'easy' },
    { word: 'بوته', category: 'طبیعت', difficulty: 'easy' },
    { word: 'برنج', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'گندم', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'جو', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'آرد', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'خمیر', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'روغن', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'شکر', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'قند', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'نمک', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'سالاد', category: 'خوراکی‌ها', difficulty: 'easy' },
    { word: 'عطر', category: 'پوشاک', difficulty: 'easy' },
    { word: 'رژ', category: 'پوشاک', difficulty: 'easy' },
    { word: 'لاک', category: 'پوشاک', difficulty: 'easy' },
    { word: 'پروانه', category: 'حیوانات', difficulty: 'easy' },
    { word: 'عنکبوت', category: 'حیوانات', difficulty: 'easy' },
    { word: 'خرچنگ', category: 'حیوانات', difficulty: 'easy' },
    { word: 'صدف', category: 'حیوانات', difficulty: 'easy' },
    { word: 'لاکپشت', category: 'حیوانات', difficulty: 'easy' },
    { word: 'طوطی', category: 'حیوانات', difficulty: 'easy' },
    { word: 'ببر', category: 'حیوانات', difficulty: 'easy' },
    { word: 'گرگ', category: 'حیوانات', difficulty: 'easy' },
    { word: 'روباه', category: 'حیوانات', difficulty: 'easy' },
    { word: 'پنگوئن', category: 'حیوانات', difficulty: 'easy' },
    { word: 'میمون', category: 'حیوانات', difficulty: 'easy' },
    { word: 'فیل', category: 'حیوانات', difficulty: 'easy' },
    { word: 'خرس', category: 'حیوانات', difficulty: 'easy' },
    { word: 'زرافه', category: 'حیوانات', difficulty: 'easy' },
    { word: 'شتر', category: 'حیوانات', difficulty: 'easy' },
    { word: 'پیانو', category: 'موسیقی', difficulty: 'easy' },
    { word: 'گیتار', category: 'موسیقی', difficulty: 'easy' },
    { word: 'بادبادک', category: 'ورزش و بازی', difficulty: 'easy' },
    { word: 'شطرنج', category: 'ورزش و بازی', difficulty: 'easy' },
    { word: 'دوربین', category: 'تکنولوژی', difficulty: 'easy' },
    { word: 'اتو', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'پنکه', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کولر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'یخچال', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'فر', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'دوش', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'وان', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'کمربند', category: 'پوشاک', difficulty: 'easy' },
    { word: 'کراوات', category: 'پوشاک', difficulty: 'easy' },
    { word: 'انگشتر', category: 'پوشاک', difficulty: 'easy' },
    { word: 'دستبند', category: 'پوشاک', difficulty: 'easy' },
    { word: 'گوشواره', category: 'پوشاک', difficulty: 'easy' },
    { word: 'چکمه', category: 'پوشاک', difficulty: 'easy' },
    { word: 'صندل', category: 'پوشاک', difficulty: 'easy' },
    { word: 'دمپایی', category: 'پوشاک', difficulty: 'easy' },
    { word: 'کاپشن', category: 'پوشاک', difficulty: 'easy' },
    { word: 'پمپ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'دنده', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'تشت', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'اسفنج', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'ماگ', category: 'اشیا و ابزار', difficulty: 'easy' },
    { word: 'آناناس', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'نارگیل', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کیوی', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'انبه', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'آووکادو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'زردآلو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'آلبالو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'انجیر', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'بادمجان', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کدو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'فلفل', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کلم', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کاهو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'ذرت', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'بلال', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'زیتون', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'پسته', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'بادام', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'گردو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'فندق', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'تخمه', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'تربچه', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'اسفناج', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کرفس', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'شلغم', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'لبو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'نخود', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'لوبیا', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'عدس', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'باقلا', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'دونات', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'پنکیک', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'وافل', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'پیراشکی', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'استیک', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'جوجه', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کوبیده', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کتلت', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کوکو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'فلافل', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'سمبوسه', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'ماکارونی', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'پاستا', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'لازانیا', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'حلیم', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'دیزی', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'املت', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'پاستیل', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'لواشک', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'پاپکورن', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'نوتلا', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'نسکافه', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'اسپرسو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'لاته', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'موکا', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کاپوچینو', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'اسموتی', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'شربت', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'ترشی', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'سرکه', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'سس', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'خردل', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'مایونز', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کچاپ', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'ژله', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کارامل', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'پودینگ', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'فرنی', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'حلوا', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'پلنگ', category: 'حیوانات', difficulty: 'medium' },
    { word: 'یوزپلنگ', category: 'حیوانات', difficulty: 'medium' },
    { word: 'شغال', category: 'حیوانات', difficulty: 'medium' },
    { word: 'پاندا', category: 'حیوانات', difficulty: 'medium' },
    { word: 'گوریل', category: 'حیوانات', difficulty: 'medium' },
    { word: 'شامپانزه', category: 'حیوانات', difficulty: 'medium' },
    { word: 'گوزن', category: 'حیوانات', difficulty: 'medium' },
    { word: 'آهو', category: 'حیوانات', difficulty: 'medium' },
    { word: 'گورخر', category: 'حیوانات', difficulty: 'medium' },
    { word: 'کانگورو', category: 'حیوانات', difficulty: 'medium' },
    { word: 'کوالا', category: 'حیوانات', difficulty: 'medium' },
    { word: 'همستر', category: 'حیوانات', difficulty: 'medium' },
    { word: 'سنجاب', category: 'حیوانات', difficulty: 'medium' },
    { word: 'خوک', category: 'حیوانات', difficulty: 'medium' },
    { word: 'خفاش', category: 'حیوانات', difficulty: 'medium' },
    { word: 'کاسکو', category: 'حیوانات', difficulty: 'medium' },
    { word: 'قناری', category: 'حیوانات', difficulty: 'medium' },
    { word: 'بلبل', category: 'حیوانات', difficulty: 'medium' },
    { word: 'کلاغ', category: 'حیوانات', difficulty: 'medium' },
    { word: 'طاووس', category: 'حیوانات', difficulty: 'medium' },
    { word: 'بوقلمون', category: 'حیوانات', difficulty: 'medium' },
    { word: 'عقاب', category: 'حیوانات', difficulty: 'medium' },
    { word: 'شاهین', category: 'حیوانات', difficulty: 'medium' },
    { word: 'جغد', category: 'حیوانات', difficulty: 'medium' },
    { word: 'کوسه', category: 'حیوانات', difficulty: 'medium' },
    { word: 'دلفین', category: 'حیوانات', difficulty: 'medium' },
    { word: 'نهنگ', category: 'حیوانات', difficulty: 'medium' },
    { word: 'وال', category: 'حیوانات', difficulty: 'medium' },
    { word: 'میگو', category: 'حیوانات', difficulty: 'medium' },
    { word: 'تمساح', category: 'حیوانات', difficulty: 'medium' },
    { word: 'مارمولک', category: 'حیوانات', difficulty: 'medium' },
    { word: 'زنبور', category: 'حیوانات', difficulty: 'medium' },
    { word: 'مگس', category: 'حیوانات', difficulty: 'medium' },
    { word: 'پشه', category: 'حیوانات', difficulty: 'medium' },
    { word: 'سوسک', category: 'حیوانات', difficulty: 'medium' },
    { word: 'مورچه', category: 'حیوانات', difficulty: 'medium' },
    { word: 'ملخ', category: 'حیوانات', difficulty: 'medium' },
    { word: 'حلزون', category: 'حیوانات', difficulty: 'medium' },
    { word: 'کرم', category: 'حیوانات', difficulty: 'medium' },
    { word: 'کفگیر', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'ملاقه', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'رنده', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'پیشبند', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'سشوار', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'بخاری', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'شومینه', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'فانوس', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'پادری', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'دراور', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'لحاف', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'تی', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'فریزر', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'اجاق', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'سینک', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'روشویی', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'توالت', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'سیفون', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'شلنگ', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'پریز', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'آهنربا', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'اسکاچ', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'آبکش', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'صافی', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'الک', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'وردنه', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'قیف', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'قفسه', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'نردبان', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'سوزن', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'نخ', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'سیگار', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'منقل', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'بادبزن', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'پرینتر', category: 'تکنولوژی', difficulty: 'medium' },
    { word: 'اسکنر', category: 'تکنولوژی', difficulty: 'medium' },
    { word: 'پروژکتور', category: 'تکنولوژی', difficulty: 'medium' },
    { word: 'آنتن', category: 'تکنولوژی', difficulty: 'medium' },
    { word: 'دیش', category: 'تکنولوژی', difficulty: 'medium' },
    { word: 'ربات', category: 'تکنولوژی', difficulty: 'medium' },
    { word: 'پهپاد', category: 'تکنولوژی', difficulty: 'medium' },
    { word: 'باتری', category: 'تکنولوژی', difficulty: 'medium' },
    { word: 'شلوارک', category: 'پوشاک', difficulty: 'medium' },
    { word: 'هودی', category: 'پوشاک', difficulty: 'medium' },
    { word: 'پالتو', category: 'پوشاک', difficulty: 'medium' },
    { word: 'جلیقه', category: 'پوشاک', difficulty: 'medium' },
    { word: 'بارانی', category: 'پوشاک', difficulty: 'medium' },
    { word: 'بلوز', category: 'پوشاک', difficulty: 'medium' },
    { word: 'تاپ', category: 'پوشاک', difficulty: 'medium' },
    { word: 'کپ', category: 'پوشاک', difficulty: 'medium' },
    { word: 'مقنعه', category: 'پوشاک', difficulty: 'medium' },
    { word: 'کتانی', category: 'پوشاک', difficulty: 'medium' },
    { word: 'پوتین', category: 'پوشاک', difficulty: 'medium' },
    { word: 'سگک', category: 'پوشاک', difficulty: 'medium' },
    { word: 'پاپیون', category: 'پوشاک', difficulty: 'medium' },
    { word: 'دکمه', category: 'پوشاک', difficulty: 'medium' },
    { word: 'زیپ', category: 'پوشاک', difficulty: 'medium' },
    { word: 'جیب', category: 'پوشاک', difficulty: 'medium' },
    { word: 'ماسک', category: 'پوشاک', difficulty: 'medium' },
    { word: 'نقاب', category: 'پوشاک', difficulty: 'medium' },
    { word: 'حلقه', category: 'پوشاک', difficulty: 'medium' },
    { word: 'گردنبند', category: 'پوشاک', difficulty: 'medium' },
    { word: 'النگو', category: 'پوشاک', difficulty: 'medium' },
    { word: 'چمدان', category: 'پوشاک', difficulty: 'medium' },
    { word: 'ساک', category: 'پوشاک', difficulty: 'medium' },
    { word: 'مینیبوس', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'ون', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'مترو', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'واگن', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'کامیون', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'تریلی', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'وانت', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'نیسان', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'تراکتور', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'لودر', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'بولدوزر', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'جرثقیل', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'آمبولانس', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'آتشنشانی', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'وسپا', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'اسکوتر', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'اسکیت', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'کالسکه', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'هلیکوپتر', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'بالن', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'موشک', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'سفینه', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'لنج', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'زیردریایی', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'سورتمه', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'ویلچر', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'برانکارد', category: 'وسایل نقلیه', difficulty: 'medium' },
    { word: 'صخره', category: 'طبیعت', difficulty: 'medium' },
    { word: 'آبشار', category: 'طبیعت', difficulty: 'medium' },
    { word: 'چشمه', category: 'طبیعت', difficulty: 'medium' },
    { word: 'برکه', category: 'طبیعت', difficulty: 'medium' },
    { word: 'دریاچه', category: 'طبیعت', difficulty: 'medium' },
    { word: 'ساحل', category: 'طبیعت', difficulty: 'medium' },
    { word: 'جزیره', category: 'طبیعت', difficulty: 'medium' },
    { word: 'غار', category: 'طبیعت', difficulty: 'medium' },
    { word: 'جنگل', category: 'طبیعت', difficulty: 'medium' },
    { word: 'کویر', category: 'طبیعت', difficulty: 'medium' },
    { word: 'کاکتوس', category: 'طبیعت', difficulty: 'medium' },
    { word: 'نخل', category: 'طبیعت', difficulty: 'medium' },
    { word: 'کاج', category: 'طبیعت', difficulty: 'medium' },
    { word: 'بامبو', category: 'طبیعت', difficulty: 'medium' },
    { word: 'رز', category: 'طبیعت', difficulty: 'medium' },
    { word: 'لاله', category: 'طبیعت', difficulty: 'medium' },
    { word: 'نرگس', category: 'طبیعت', difficulty: 'medium' },
    { word: 'یاس', category: 'طبیعت', difficulty: 'medium' },
    { word: 'آفتابگردان', category: 'طبیعت', difficulty: 'medium' },
    { word: 'الماس', category: 'طبیعت', difficulty: 'medium' },
    { word: 'طلا', category: 'طبیعت', difficulty: 'medium' },
    { word: 'نقره', category: 'طبیعت', difficulty: 'medium' },
    { word: 'شن', category: 'طبیعت', difficulty: 'medium' },
    { word: 'ماسه', category: 'طبیعت', difficulty: 'medium' },
    { word: 'خاک', category: 'طبیعت', difficulty: 'medium' },
    { word: 'یخ', category: 'طبیعت', difficulty: 'medium' },
    { word: 'کلبه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'ویلا', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'آپارتمان', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'کاخ', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'قلعه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'برج', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'کلیسا', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'دانشگاه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'کتابخانه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'فرودگاه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'ایستگاه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'اسکله', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'بندر', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'تونل', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'سد', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'استادیوم', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'شهربازی', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'سیرک', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'سینما', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'تئاتر', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'موزه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'رستوران', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'کافه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'فروشگاه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'سوپرمارکت', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'نانوایی', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'قصابی', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'کارخانه', category: 'ساختمان و مکان', difficulty: 'medium' },
    { word: 'راکت', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'دمبل', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'هالتر', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'وزنه', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'کایت', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'یویو', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'فرفره', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'تیله', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'دومینو', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'پاسور', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'منچ', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'پازل', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'لگو', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'دارت', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'تردمیل', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'سرسره', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'تاب', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'الاکلنگ', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'اسکی', category: 'ورزش و بازی', difficulty: 'medium' },
    { word: 'پرستار', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'مهندس', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'عکاس', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'قصاب', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'آتشنشان', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'ملوان', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'ناخدا', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'کاپیتان', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'خیاط', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'آرایشگر', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'باغبان', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'کشاورز', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'مکانیک', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'جوشکار', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'کارگر', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'فضانورد', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'دانشمند', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'چوپان', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'پستچی', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'راننده', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'خواننده', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'نوازنده', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'شعبدهباز', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'کارآگاه', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'شاهزاده', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'پرنسس', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'فرشته', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'پری', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'دیو', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'غول', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'جادوگر', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'مترسک', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'اسکلت', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'روح', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'شبح', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'نینجا', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'سامورایی', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'شوالیه', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'کابوی', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'کلانتر', category: 'شخصیت‌ها و مشاغل', difficulty: 'medium' },
    { word: 'فلوت', category: 'موسیقی', difficulty: 'medium' },
    { word: 'تار', category: 'موسیقی', difficulty: 'medium' },
    { word: 'صاعقه', category: 'طبیعت', difficulty: 'medium' },
    { word: 'شهاب', category: 'طبیعت', difficulty: 'medium' },
    { word: 'خارپشت', category: 'حیوانات', difficulty: 'medium' },
    { word: 'میکسر', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'بلندر', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'هود', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'دوشاخه', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'تمشک', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'کشمش', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'راسو', category: 'حیوانات', difficulty: 'medium' },
    { word: 'لاما', category: 'حیوانات', difficulty: 'medium' },
    { word: 'قمری', category: 'حیوانات', difficulty: 'medium' },
    { word: 'سوسمار', category: 'حیوانات', difficulty: 'medium' },
    { word: 'قالیچه', category: 'اشیا و ابزار', difficulty: 'medium' },
    { word: 'زردچوبه', category: 'خوراکی‌ها', difficulty: 'medium' },
    { word: 'باقلوا', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'گز', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'سوهان', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'قطاب', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'پشمک', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'زولبیا', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'بامیه', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'فالوده', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'سمنو', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'کوفته', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'دلمه', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'تهدیگ', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'قیمه', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'فسنجان', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'سنگک', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'بربری', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'لواش', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'تافتون', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'تیرامیسو', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'تارت', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'مافین', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'کرگدن', category: 'حیوانات', difficulty: 'hard' },
    { word: 'آفتابپرست', category: 'حیوانات', difficulty: 'hard' },
    { word: 'کفتار', category: 'حیوانات', difficulty: 'hard' },
    { word: 'قاطر', category: 'حیوانات', difficulty: 'hard' },
    { word: 'قوچ', category: 'حیوانات', difficulty: 'hard' },
    { word: 'هدهد', category: 'حیوانات', difficulty: 'hard' },
    { word: 'دارکوب', category: 'حیوانات', difficulty: 'hard' },
    { word: 'قرقاول', category: 'حیوانات', difficulty: 'hard' },
    { word: 'لکلک', category: 'حیوانات', difficulty: 'hard' },
    { word: 'پلیکان', category: 'حیوانات', difficulty: 'hard' },
    { word: 'فلامینگو', category: 'حیوانات', difficulty: 'hard' },
    { word: 'کرکس', category: 'حیوانات', difficulty: 'hard' },
    { word: 'لاشخور', category: 'حیوانات', difficulty: 'hard' },
    { word: 'پرستو', category: 'حیوانات', difficulty: 'hard' },
    { word: 'سار', category: 'حیوانات', difficulty: 'hard' },
    { word: 'اختاپوس', category: 'حیوانات', difficulty: 'hard' },
    { word: 'هشتپا', category: 'حیوانات', difficulty: 'hard' },
    { word: 'وزغ', category: 'حیوانات', difficulty: 'hard' },
    { word: 'کبرا', category: 'حیوانات', difficulty: 'hard' },
    { word: 'پایتون', category: 'حیوانات', difficulty: 'hard' },
    { word: 'شاپرک', category: 'حیوانات', difficulty: 'hard' },
    { word: 'سنجاقک', category: 'حیوانات', difficulty: 'hard' },
    { word: 'عقرب', category: 'حیوانات', difficulty: 'hard' },
    { word: 'هزارپا', category: 'حیوانات', difficulty: 'hard' },
    { word: 'رتیل', category: 'حیوانات', difficulty: 'hard' },
    { word: 'سمور', category: 'حیوانات', difficulty: 'hard' },
    { word: 'فوک', category: 'حیوانات', difficulty: 'hard' },
    { word: 'اورکا', category: 'حیوانات', difficulty: 'hard' },
    { word: 'دیناسور', category: 'حیوانات', difficulty: 'hard' },
    { word: 'لوستر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'آباژور', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'رادیاتور', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'گاوصندوق', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'دماسنج', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تایمر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'انگشتانه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'ماسوره', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'دوک', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'بشکاف', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'آفتابه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'لگن', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تلمبه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تله', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'زنگوله', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'چشمی', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'گونیا', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تراز', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'شاغول', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'سندان', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'کاردک', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'ماله', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'کمچه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'پیستوله', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'کمپرسور', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'جک', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'قرقره', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'بلبرینگ', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'میکروسکوپ', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تلسکوپ', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'قطبنما', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'نقاله', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'مونوپاد', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'ماهواره', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'تراشه', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'هارد', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'لیزر', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'تاج', category: 'پوشاک', difficulty: 'hard' },
    { word: 'کاسکت', category: 'پوشاک', difficulty: 'hard' },
    { word: 'کلاهخود', category: 'پوشاک', difficulty: 'hard' },
    { word: 'مدال', category: 'پوشاک', difficulty: 'hard' },
    { word: 'پابند', category: 'پوشاک', difficulty: 'hard' },
    { word: 'خلخال', category: 'پوشاک', difficulty: 'hard' },
    { word: 'شنل', category: 'پوشاک', difficulty: 'hard' },
    { word: 'مایو', category: 'پوشاک', difficulty: 'hard' },
    { word: 'یونیفرم', category: 'پوشاک', difficulty: 'hard' },
    { word: 'بادگیر', category: 'پوشاک', difficulty: 'hard' },
    { word: 'گیوه', category: 'پوشاک', difficulty: 'hard' },
    { word: 'چاروق', category: 'پوشاک', difficulty: 'hard' },
    { word: 'تراموا', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'لکوموتیو', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'هاوربرد', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'درشکه', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'گاری', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'ارابه', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'هاورکرافت', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'تلهکابین', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'تلهسیژ', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'مونوریل', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'کانو', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'کایاک', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'کلک', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'ناو', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'گلایدر', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'پاراگلایدر', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'فضاپیما', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'شاتل', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'آتشفشان', category: 'طبیعت', difficulty: 'hard' },
    { word: 'گردباد', category: 'طبیعت', difficulty: 'hard' },
    { word: 'طوفان', category: 'طبیعت', difficulty: 'hard' },
    { word: 'نیلوفر', category: 'طبیعت', difficulty: 'hard' },
    { word: 'ارکیده', category: 'طبیعت', difficulty: 'hard' },
    { word: 'شقایق', category: 'طبیعت', difficulty: 'hard' },
    { word: 'بنفشه', category: 'طبیعت', difficulty: 'hard' },
    { word: 'بلوط', category: 'طبیعت', difficulty: 'hard' },
    { word: 'صنوبر', category: 'طبیعت', difficulty: 'hard' },
    { word: 'بیدمجنون', category: 'طبیعت', difficulty: 'hard' },
    { word: 'قندیل', category: 'طبیعت', difficulty: 'hard' },
    { word: 'مروارید', category: 'طبیعت', difficulty: 'hard' },
    { word: 'یاقوت', category: 'طبیعت', difficulty: 'hard' },
    { word: 'زمرد', category: 'طبیعت', difficulty: 'hard' },
    { word: 'فیروزه', category: 'طبیعت', difficulty: 'hard' },
    { word: 'عقیق', category: 'طبیعت', difficulty: 'hard' },
    { word: 'کهربا', category: 'طبیعت', difficulty: 'hard' },
    { word: 'کریستال', category: 'طبیعت', difficulty: 'hard' },
    { word: 'زغال', category: 'طبیعت', difficulty: 'hard' },
    { word: 'مرجان', category: 'طبیعت', difficulty: 'hard' },
    { word: 'آسیاب', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'گلخانه', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'آکواریوم', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'باغوحش', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'معبد', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'اهرام', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'هرم', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'ابوالهول', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'کاروانسرا', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'قنات', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'چاه', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'ایگلو', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'آلاچیق', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'سنگر', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'پناهگاه', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'مناره', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'گنبد', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'محراب', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'بارو', category: 'ساختمان و مکان', difficulty: 'hard' },
    { word: 'روبیک', category: 'ورزش و بازی', difficulty: 'hard' },
    { word: 'بولینگ', category: 'ورزش و بازی', difficulty: 'hard' },
    { word: 'بیلیارد', category: 'ورزش و بازی', difficulty: 'hard' },
    { word: 'ترامپولین', category: 'ورزش و بازی', difficulty: 'hard' },
    { word: 'فین', category: 'ورزش و بازی', difficulty: 'hard' },
    { word: 'غواص', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'باستانشناس', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'آهنگر', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'گلادیاتور', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'وایکینگ', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'فرعون', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'امپراتور', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'درویش', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'دراکولا', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'زامبی', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'مومیایی', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'بیگانه', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'فضایی', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'پینوکیو', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'سندباد', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'علاءالدین', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'تارزان', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'زورو', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'شرلوک', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'بتمن', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'سوپرمن', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'هالک', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'جوکر', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'باباسفنجی', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'پاتریک', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'شرک', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'مینیون', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'گوفی', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'تام', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'جری', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'پلنگصورتی', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'رستم', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'سهراب', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'سیمرغ', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'آرش', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'ماریو', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'سونیک', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'پیکاچو', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'ویولن', category: 'موسیقی', difficulty: 'hard' },
    { word: 'سنتور', category: 'موسیقی', difficulty: 'hard' },
    { word: 'کمانچه', category: 'موسیقی', difficulty: 'hard' },
    { word: 'ترومپت', category: 'موسیقی', difficulty: 'hard' },
    { word: 'ساکسیفون', category: 'موسیقی', difficulty: 'hard' },
    { word: 'چنگ', category: 'موسیقی', difficulty: 'hard' },
    { word: 'دهل', category: 'موسیقی', difficulty: 'hard' },
    { word: 'کاخن', category: 'موسیقی', difficulty: 'hard' },
    { word: 'ناقوس', category: 'موسیقی', difficulty: 'hard' },
    { word: 'اکاردئون', category: 'موسیقی', difficulty: 'hard' },
    { word: 'عود', category: 'موسیقی', difficulty: 'hard' },
    { word: 'پنجه', category: 'اعضای بدن', difficulty: 'hard' },
    { word: 'عاج', category: 'اعضای بدن', difficulty: 'hard' },
    { word: 'جمجمه', category: 'اعضای بدن', difficulty: 'hard' },
    { word: 'مسلسل', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'کلاشینکف', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'اسنایپر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'فشنگ', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'خشاب', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'مین', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'فلاخن', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'گرز', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'منجنیق', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'هاون', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'فلاسک', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'همزن', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'توستر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'ماکروویو', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'ترازو', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'بلندگو', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'بوق', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'شیپور', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'آژیر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'قلیان', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'پیپ', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'باربیکیو', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'انبر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'شمعدان', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'مهره', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'واشر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'آچار', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'انبردست', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'فازمتر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'دریل', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'مته', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'متر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'خطکش', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'پرگار', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'فرغون', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'داس', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تیشه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'کاتر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تیغ', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'منگنه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'پونز', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'گیره', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'جامدادی', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'خودنویس', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'ماژیک', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'مقوا', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'پوشه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'کلاسور', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'بوم', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'پالت', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'قلممو', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'آبرنگ', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'گواش', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'نقشه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'ذرهبین', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تبلت', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'مانیتور', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'کیبورد', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'ماوس', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'اسپیکر', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'هدفون', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'هندزفری', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'ایرپاد', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'هدست', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'میکروفون', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'لنز', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'وبکم', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'شارژر', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'کابل', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'سیم', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'فلش', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'مودم', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'کنسول', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'گیمپد', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'جویستیک', category: 'تکنولوژی', difficulty: 'hard' },
    { word: 'فشارسنج', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'بادسنج', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'شاقول', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'سمباده', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'اسپری', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تپانچه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'شاتگان', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'خنجر', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'زره', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'نیزه', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'خمره', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'مشک', category: 'اشیا و ابزار', difficulty: 'hard' },
    { word: 'تشی', category: 'حیوانات', difficulty: 'hard' },
    { word: 'پاراشوت', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'جراح', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'آهنگساز', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'قانون', category: 'موسیقی', difficulty: 'hard' },
    { word: 'بربط', category: 'موسیقی', difficulty: 'hard' },
    { word: 'رباب', category: 'موسیقی', difficulty: 'hard' },
    { word: 'کرنا', category: 'موسیقی', difficulty: 'hard' },
    { word: 'سرنا', category: 'موسیقی', difficulty: 'hard' },
    { word: 'گدازه', category: 'طبیعت', difficulty: 'hard' },
    { word: 'سونامی', category: 'طبیعت', difficulty: 'hard' },
    { word: 'کهکشان', category: 'طبیعت', difficulty: 'hard' },
    { word: 'سحابی', category: 'طبیعت', difficulty: 'hard' },
    { word: 'سمندر', category: 'حیوانات', difficulty: 'hard' },
    { word: 'قلیه', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'مسقطی', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'کاکائو', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'آویشن', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'سماق', category: 'خوراکی‌ها', difficulty: 'hard' },
    { word: 'کاوشگر', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'کارتینگ', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'بادبان', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'لنگر', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'سکان', category: 'وسایل نقلیه', difficulty: 'hard' },
    { word: 'کوهنورد', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'تیرانداز', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'کماندار', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'شناگر', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'بوکسور', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
    { word: 'دونده', category: 'شخصیت‌ها و مشاغل', difficulty: 'hard' },
  ];

  /**
   * Persian text normalizer for accurate, fair guess evaluation.
   */
  function normalizePersian(text) {
    if (!text || typeof text !== 'string') return '';
    let s = text.trim().toLowerCase();

    // Replace zero-width spaces and ZWNJ with space to preserve word boundary
    s = s.replace(/[\u200B-\u200F\u202A-\u202E\uFEFF]/g, ' ');

    // Remove Tatweel / Kashida (ـ)
    s = s.replace(/\u0640/g, '');

    // Remove Arabic Harakat / Diacritics
    s = s.replace(/[\u064B-\u065F\u0670]/g, '');

    // Unify Persian / Arabic letter variants
    s = s
      .replace(/[يى]/g, 'ی')
      .replace(/[ك]/g, 'ک')
      .replace(/[ة]/g, 'ه')
      .replace(/[ؤ]/g, 'و')
      .replace(/[إأآٱ]/g, 'ا')
      .replace(/[ئ]/g, 'ی');

    // Remove common Persian/English punctuation
    s = s.replace(/[.,\/#!$%\^&\*;:{}=\-_~`()؟?!،«»"']/g, ' ');

    // Normalize multiple spaces into single space
    s = s.replace(/\s+/g, ' ').trim();

    return s;
  }

  /**
   * Normalized comparison without spaces (so 'برنامه نویس' equals 'برنامه‌نویس' and 'برنامهنویس')
   */
  function normalizeCompact(text) {
    return normalizePersian(text).replace(/\s+/g, '');
  }

  /**
   * Calculate Levenshtein distance between two strings
   */
  function levenshtein(a, b) {
    const matrix = [];
    for (let i = 0; i <= b.length; i++) {
      matrix[i] = [i];
    }
    for (let j = 0; j <= a.length; j++) {
      matrix[0][j] = j;
    }
    for (let i = 1; i <= b.length; i++) {
      for (let j = 1; j <= a.length; j++) {
        if (b.charAt(i - 1) === a.charAt(j - 1)) {
          matrix[i][j] = matrix[i - 1][j - 1];
        } else {
          matrix[i][j] = Math.min(
            matrix[i - 1][j - 1] + 1, // substitution
            matrix[i][j - 1] + 1,     // insertion
            matrix[i - 1][j] + 1      // deletion
          );
        }
      }
    }
    return matrix[b.length][a.length];
  }

  /**
   * Check if user's guess matches the target word.
   */
  function checkGuess(guess, targetWord) {
    if (!guess || !targetWord) return { isCorrect: false, isClose: false };

    const normGuess = normalizeCompact(guess);
    const normTarget = normalizeCompact(targetWord);

    if (normGuess === normTarget) {
      return { isCorrect: true, isClose: false };
    }

    // Check if close (Levenshtein distance == 1 for words with 4+ characters)
    if (normTarget.length >= 4) {
      const dist = levenshtein(normGuess, normTarget);
      if (dist === 1) {
        return { isCorrect: false, isClose: true };
      }
    }

    return { isCorrect: false, isClose: false };
  }

  /**
   * Generates a masked representation of a word for guessers.
   * Example: 'سیب' -> '_ _ _'
   * Example with letter revealed at index 1: 'س _ _'
   */
  function getMaskedDisplay(word, revealedIndices = new Set()) {
    if (!word) return '';
    const chars = Array.from(word);
    const masked = chars.map((ch, idx) => {
      if (ch === ' ' || ch === '‌' || ch === '-') {
        return '   '; // Visible gap for word separation
      }
      if (revealedIndices && (revealedIndices.has(idx) || (typeof revealedIndices.includes === 'function' && revealedIndices.includes(idx)))) {
        return ch;
      }
      return '_';
    });
    return masked.join(' ');
  }

  /**
   * Selects an unrevealed letter index for hint system
   */
  function getNextHintIndex(word, alreadyRevealed = new Set()) {
    const chars = Array.from(word);
    const candidates = [];
    chars.forEach((ch, idx) => {
      const isAlready = alreadyRevealed instanceof Set ? alreadyRevealed.has(idx) : Array.isArray(alreadyRevealed) ? alreadyRevealed.includes(idx) : false;
      if (ch !== ' ' && ch !== '‌' && ch !== '-' && !isAlready) {
        candidates.push(idx);
      }
    });
    if (candidates.length === 0) return null;
    return candidates[Math.floor(Math.random() * candidates.length)];
  }

  /**
   * Pick 3 words of balanced difficulty (1 Easy, 1 Medium, 1 Hard) for the drawer to choose from.
   * Features true uniform randomness and excludes recently used words to prevent repetition.
   */
  function pickWordChoices(usedWordList = []) {
    const usedSet = new Set(usedWordList || []);

    const easyWords = WORDS.filter(w => w.difficulty === 'easy');
    const medWords = WORDS.filter(w => w.difficulty === 'medium');
    const hardWords = WORDS.filter(w => w.difficulty === 'hard');

    let availEasy = easyWords.filter(w => !usedSet.has(w.word));
    let availMed = medWords.filter(w => !usedSet.has(w.word));
    let availHard = hardWords.filter(w => !usedSet.has(w.word));

    if (availEasy.length === 0) availEasy = easyWords;
    if (availMed.length === 0) availMed = medWords;
    if (availHard.length === 0) availHard = hardWords;

    const pickRandom = (arr, excludeSet) => {
      const pool = excludeSet ? arr.filter(w => !excludeSet.has(w.word)) : arr;
      const finalPool = pool.length > 0 ? pool : arr;
      const idx = Math.floor(Math.random() * finalPool.length);
      return finalPool[idx];
    };

    const easy = pickRandom(availEasy);
    const chosenSet = new Set([easy.word]);

    const med = pickRandom(availMed, chosenSet);
    chosenSet.add(med.word);

    const hard = pickRandom(availHard, chosenSet);

    // Strictly returns 1 Easy, 1 Medium, 1 Hard
    return [easy, med, hard];
  }

  return {
    WORDS,
    normalizePersian,
    normalizeCompact,
    levenshtein,
    checkGuess,
    getMaskedDisplay,
    getNextHintIndex,
    pickWordChoices
  };
});
